// flow-typed signature: 94fb3c040a8e22e536e52a1d2227379e
// flow-typed version: <<STUB>>/graceful-fs_v4.x/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graceful-fs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graceful-fs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graceful-fs/fs' {
  declare module.exports: any;
}

declare module 'graceful-fs/graceful-fs' {
  declare module.exports: any;
}

declare module 'graceful-fs/legacy-streams' {
  declare module.exports: any;
}

declare module 'graceful-fs/polyfills' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graceful-fs/fs.js' {
  declare module.exports: $Exports<'graceful-fs/fs'>;
}
declare module 'graceful-fs/graceful-fs.js' {
  declare module.exports: $Exports<'graceful-fs/graceful-fs'>;
}
declare module 'graceful-fs/legacy-streams.js' {
  declare module.exports: $Exports<'graceful-fs/legacy-streams'>;
}
declare module 'graceful-fs/polyfills.js' {
  declare module.exports: $Exports<'graceful-fs/polyfills'>;
}
